project_id = "fdxtonspmoghoaqvubqf"

[functions.send-contact-form]
verify_jwt = false

[functions.get-order-details]
verify_jwt = false

[functions.payu-webhook]
verify_jwt = false

[functions.create-payu-order]
verify_jwt = false

[functions.create-hotpay-order]
verify_jwt = false

[functions.hotpay-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.cleanup-expired-carts]
verify_jwt = false

[functions.import-products]
verify_jwt = false
